// Code generated by protoc-gen-go.
// source: kite_bind.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

用于订阅关系的协议

It is generated from these files:
	kite_bind.proto
	kite_remoting.proto

It has these top-level messages:
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

func init() {
}
